[2025-01-15T12:14:29.342+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-15T12:14:29.356+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: travel_price_prediction.transform_data_task manual__2025-01-15T12:11:04.345977+00:00 [queued]>
[2025-01-15T12:14:29.379+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: travel_price_prediction.transform_data_task manual__2025-01-15T12:11:04.345977+00:00 [queued]>
[2025-01-15T12:14:29.381+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 2
[2025-01-15T12:14:29.423+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_data_task> on 2025-01-15 12:11:04.345977+00:00
[2025-01-15T12:14:29.432+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'travel_price_prediction', 'transform_data_task', 'manual__2025-01-15T12:11:04.345977+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/flight-price-pred-dag.py', '--cfg-path', '/tmp/tmpbcz6xtae']
[2025-01-15T12:14:29.433+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask transform_data_task
[2025-01-15T12:14:29.435+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-15T12:14:29.436+0000] {standard_task_runner.py:72} INFO - Started process 110 to run task
[2025-01-15T12:14:29.491+0000] {task_command.py:467} INFO - Running <TaskInstance: travel_price_prediction.transform_data_task manual__2025-01-15T12:11:04.345977+00:00 [running]> on host 3576a91a75bb
[2025-01-15T12:14:29.707+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='travel_price_prediction' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-15T12:11:04.345977+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-15T12:11:04.345977+00:00'
[2025-01-15T12:14:29.707+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-15T12:14:31.641+0000] {python.py:240} INFO - Done. Returned value was: (        is_weekend  distance  ...  agency_FlyingDrops  agency_Rainbow
230046           0  0.433676  ...                 0.0             0.0
31870            0  0.017922  ...                 0.0             0.0
77947            0  0.242478  ...                 0.0             1.0
69869            0  0.042091  ...                 0.0             1.0
215948           0 -0.385963  ...                 0.0             1.0
...            ...       ...  ...                 ...             ...
119879           0 -0.055255  ...                 0.0             0.0
259178           0  0.620183  ...                 0.0             1.0
131932           0 -0.117760  ...                 0.0             0.0
146867           0 -1.812554  ...                 0.0             0.0
121958           0 -0.117760  ...                 1.0             0.0

[203916 rows x 33 columns], 230046     636.51
31870     1313.76
77947     1386.46
69869      932.22
215948     317.08
           ...   
119879     793.15
259178    1013.40
131932    1149.38
146867     620.16
121958    1052.60
Name: price, Length: 203916, dtype: float64,         is_weekend  distance  ...  agency_FlyingDrops  agency_Rainbow
226840           0 -0.385963  ...                 0.0             1.0
31439            0  0.042091  ...                 0.0             0.0
260515           0  1.253458  ...                 0.0             0.0
265574           0  1.870461  ...                 0.0             0.0
14311            1 -0.055255  ...                 0.0             0.0
...            ...       ...  ...                 ...             ...
123032           0  0.128572  ...                 0.0             1.0
8663             1  1.358796  ...                 0.0             1.0
208594           0  0.620183  ...                 0.0             0.0
116371           1  0.128572  ...                 0.0             1.0
266509           1  0.128572  ...                 0.0             0.0

[67972 rows x 33 columns], 226840     481.42
31439     1124.11
260515    1174.97
265574     898.67
14311      959.91
           ...   
123032    1030.13
8663       826.02
208594     918.66
116371     857.32
266509    1446.34
Name: price, Length: 67972, dtype: float64)
[2025-01-15T12:14:32.276+0000] {xcom.py:690} ERROR - Object of type tuple is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2025-01-15T12:14:32.279+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 151, in serialize
    return encode(classname or serialized_classname, version, serialize(data, depth + 1))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 128, in serialize
    return [serialize(d, depth + 1) for d in o]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3639, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 103, in encode
    o = self.default(o)
        ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2025-01-15T12:14:32.294+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=travel_price_prediction, task_id=transform_data_task, run_id=manual__2025-01-15T12:11:04.345977+00:00, execution_date=20250115T121104, start_date=20250115T121429, end_date=20250115T121432
[2025-01-15T12:14:32.358+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-15T12:14:32.359+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task transform_data_task (Object of type tuple is not JSON serializable; 110)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 151, in serialize
    return encode(classname or serialized_classname, version, serialize(data, depth + 1))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 128, in serialize
    return [serialize(d, depth + 1) for d in o]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3639, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 103, in encode
    o = self.default(o)
        ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2025-01-15T12:14:32.423+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-15T12:14:32.464+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-15T12:14:32.496+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
